services:
  server:
    image: ottp-back-end-image-dev
    build:
      context: ./back-end
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./back-end:/usr/src/app
    ports:
      - "5000:5000"
    container_name: ottp-server-dev
  app:
    image: ottp-front-end-image-dev
    build:
      context: ./front-end
      dockerfile: ./dev.Dockerfile
      args:
        REACT_APP_BACKEND_URL: "/api"
    volumes:
      - ./front-end/:/usr/src/app
    ports:
      - "3000:3000"
    container_name: ottp-app-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./dev.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    container_name: ottp-reverse-proxy-dev
    depends_on:
      - app
      - server
