services:
    server:
      image: ottp-back-end-image
      build:
        context: ./back-end
        dockerfile: ./Dockerfile
      ports:
        - "8000:8080"
      container_name: ottp-server
    app:
      image: ottp-front-end-image
      build:
        context: ./front-end
        dockerfile: ./Dockerfile
        args:
          REACT_APP_BACKEND_URL: "/api"
      ports:
        - "5000:80"
      container_name: ottp-app
    nginx:
      image: nginx:1.20.1
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "8080:80"
      container_name: ottp-reverse-proxy
      depends_on:
        - app
        - server